const { MongoClient } = require('mongodb')
const client = new MongoClient('mongodb://localhost:27017')
const axios = require('axios')


module.exports = async function getProducts(paramsObj, req) {
  try {
    const result = []
    let products = null
    const paramsArrKeys = Object.keys(paramsObj)

    const { data } = await axios.get('https://api.sales-search.ru/api/selects')
    // const { data } = await axios.get('http://localhost:3001/api/selects')

    // const data = JSON.parse(JSON.stringify({
    //     "brands": [
    //       "120% LINO",
    //       "1TO3",
    //       "2 STAR",
    //       "29DESIRES",
    //       "2WOMEN",
    //       "4CCCCEES",
    //       "4G",
    //       "6 WHITE",
    //       "7 FOR ALL MANKIND",
    //       "9.2 BY CARLO CHIONNA",
    //       "A + MORE",
    //       "A-DRESS",
    //       "A.TESTONI",
    //       "ACASTA",
    //       "ACQUAVERDE",
    //       "ADA GATTI",
    //       "ADD",
    //       "ADELE FADO",
    //       "ADIDAS",
    //       "ADIDAS ORIGINALS",
    //       "ADL",
    //       "ADRIANO BARONI",
    //       "ADZHEDO",
    //       "AERONAUTICA MILITARE",
    //       "AFFEX",
    //       "AGAIN&AGAIN",
    //       "AGNONA",
    //       "AGOLDE",
    //       "AIDA BARNI",
    //       "AINEA",
    //       "AIR JORDAN",
    //       "AIRWOOL",
    //       "ALAIA",
    //       "ALBA",
    //       "ALBANO",
    //       "ALBEROTANZA",
    //       "ALBERTA FERRETTI",
    //       "ALDO",
    //       "ALDO BRUE",
    //       "ALDO BRUE`",
    //       "ALESSANDRO",
    //       "ALEX SILVA",
    //       "ALEXANDER MCQUEEN",
    //       "ALEXANDER McQUEEN",
    //       "ALEXANDER WANG",
    //       "ALEXANDRA",
    //       "ALEXANDRE VAUTHIER",
    //       "ALFA BETTA",
    //       "ALLA BUONE",
    //       "ALLSAINTS",
    //       "ALLTIMERS",
    //       "ALOHAS",
    //       "ALPHA INDUSTRIES",
    //       "ALTEA",
    //       "ALTER EGO",
    //       "AMAZONGA",
    //       "AMBIGANTE",
    //       "AMEDEO FERRANTE",
    //       "AMERICAN LEGEND",
    //       "AMORALLE",
    //       "AMULET",
    //       "ANA.R",
    //       "AND THE BRAND",
    //       "ANDREA MORELLI",
    //       "ANDREA PINTO",
    //       "ANDREA YA’AQOV",
    //       "ANESIA",
    //       "ANGEL",
    //       "ANGEL STORY",
    //       "ANGELO MILANO",
    //       "ANNALISA",
    //       "ANNE MICHELLE",
    //       "ANNECLAIRE",
    //       "ANTONELLI FIRENZE",
    //       "ANTONIO BERARDI",
    //       "ANTONIO BIAGGI",
    //       "ANTONIO SIANO",
    //       "APEPAZZA",
    //       "AQUAZZURA",
    //       "AREFEVA",
    //       "ARINA BALLERINA",
    //       "ARMANI",
    //       "ARMANI EXCHANGE",
    //       "ARMANI JEANS",
    //       "ART OF SOUL",
    //       "ARTIE",
    //       "ARTIOLI",
    //       "ARUNA BLU",
    //       "ARZOmania",
    //       "ASH",
    //       "ASICS",
    //       "ASPAYA",
    //       "ASTRID BRYAN",
    //       "ATOS LOMBARDINI",
    //       "ATTOLINI",
    //       "AURORA FIRENZE",
    //       "AVENIR",
    //       "AVI",
    //       "AXARA PARIS",
    //       "AXEL ARIGATO",
    //       "Amore Amore",
    //       "BA&SH",
    //       "BAD CAT",
    //       "BADEN",
    //       "BAGATT",
    //       "BALD EAGLE",
    //       "BALDAN",
    //       "BALDESSARINI",
    //       "BALDI",
    //       "BALDININI",
    //       "BALENCIAGA",
    //       "BALEX GRAND",
    //       "BALLANTYNE",
    //       "BALLY",
    //       "BALMAIN",
    //       "BALUNOVA",
    //       "BANANA REPUBLIC",
    //       "BAON",
    //       "BARBA",
    //       "BARBIE",
    //       "BARMAS JEANS",
    //       "BARRACUDA",
    //       "BARRETT",
    //       "BASCONI",
    //       "BASTOM",
    //       "BATA",
    //       "BAZAR DELUXE",
    //       "BCONB",
    //       "BE MINE",
    //       "BEBE",
    //       "BEBENDORFF",
    //       "BEFREE",
    //       "BEIRA RIO",
    //       "BEIWEISI",
    //       "BEL",
    //       "BELL BIMBO",
    //       "BELLAMICA",
    //       "BELLINI",
    //       "BELLO PASSO",
    //       "BELUCCI",
    //       "BELWEST",
    //       "BENETTON",
    //       "BENETTON UNDERCOLORS",
    //       "BENINI",
    //       "BERTOLO LUXURY MENSWEAR",
    //       "BERWICH",
    //       "BEST CONNECTIONS",
    //       "BEST MOUNTAINE",
    //       "BESTIA",
    //       "BETSY",
    //       "BETTY & CO",
    //       "BETTY BARCLAY",
    //       "BGN",
    //       "BIBI LOU",
    //       "BILANCIONI",
    //       "BILLI BI COPENHAGEN",
    //       "BILLIEBLUSH",
    //       "BILLIONAIRE",
    //       "BILLYBANDIT",
    //       "BIONDINI",
    //       "BISIBIGLIO",
    //       "BITIS",
    //       "BLANCHA",
    //       "BLAUER",
    //       "BLINK",
    //       "BLU BARRETT",
    //       "BLU BYBLOS",
    //       "BLUE BAY",
    //       "BLUE SEVEN",
    //       "BLUGIRL",
    //       "BLUMARINE",
    //       "BOBOLI",
    //       "BODYFLIRT",
    //       "BODYGUARD",
    //       "BOGI",
    //       "BOGI ACCESSORIES",
    //       "BOGNER",
    //       "BOGNER FIRE + ICE",
    //       "BONTONI",
    //       "BOOMBOOTS",
    //       "BOOMERANG",
    //       "BOOTCUT",
    //       "BORSALINO",
    //       "BOSS",
    //       "BOTTICELLI LIMITED",
    //       "BPC",
    //       "BRACCIALINI",
    //       "BRAVE SOUL",
    //       "BRAX",
    //       "BRECOS",
    //       "BRIAN DALES",
    //       "BRIGITTE BARDOT",
    //       "BRIONI",
    //       "BRIONITY",
    //       "BROADWAY",
    //       "BRONX",
    //       "BRUMS",
    //       "BRUNELLO CUCINELLI",
    //       "BRUNO BANANI",
    //       "BRUNO MANETTI",
    //       "BRUNO PREMI",
    //       "BSB",
    //       "BUGATTI",
    //       "BURBERRY",
    //       "BURLESQUE",
    //       "BURLINGTON",
    //       "BY FAR",
    //       "BY MALENE BIRGER",
    //       "BY SAIID KOBEISY",
    //       "Best&Best",
    //       "C.P. COMPANY",
    //       "CAFeNOIR",
    //       "CALL It SPRING",
    //       "CALVIN KLEIN",
    //       "CALVIN KLEIN JEANS",
    //       "CALVIN KLEIN JEANS BY CALVIN KLEIN",
    //       "CAMELOT",
    //       "CAMERLENGO",
    //       "CANALI",
    //       "CANOE",
    //       "CAP HORN",
    //       "CAPOBIANCO",
    //       "CAPPELLINI BY PESERICO",
    //       "CAPRI",
    //       "CAPRISEELITE",
    //       "CARHARTT WIP",
    //       "CARLA GIANNINI",
    //       "CARLO BELLINI",
    //       "CARLO VISINTINI",
    //       "CARMENS",
    //       "CAROLINA HERRERA",
    //       "CARTAGO",
    //       "CARTER&APOS;S",
    //       "CARVELA",
    //       "CASADEI",
    //       "CASTANER",
    //       "CASTANGIA",
    //       "CASTELLO d'ORO",
    //       "CASTORI",
    //       "CATHERINE",
    //       "CATIMINI",
    //       "CATISA",
    //       "CATNOIR",
    //       "CATTY&PERRY",
    //       "CAVO",
    //       "CERRUTI",
    //       "CHAMPION",
    //       "CHANTAL THOMASS",
    //       "CHAPURIN",
    //       "CHARLOTTE OLYMPIA",
    //       "CHARMANTE",
    //       "CHARO RUIZ",
    //       "CHASSE",
    //       "CHEZOLINY",
    //       "CHIARA BONI",
    //       "CHIARA FERRAGNI",
    //       "CHIC & SWAG",
    //       "CHINESE LAUNDRY",
    //       "CHLOE",
    //       "CHOUPETTE",
    //       "CINEMADONNA",
    //       "CIRCOLO 1901",
    //       "CLARKS ORIGINALS",
    //       "CLASS CAVALLI",
    //       "CLASS INTERNATIONAL",
    //       "CLASS INTERNATIONAL FX",
    //       "CLAUDIE PIERLOT",
    //       "CLEO",
    //       "CLEVERLY",
    //       "CLIPS",
    //       "CLOWSE",
    //       "COCCINELLE",
    //       "COCO PERLA",
    //       "COCOSHNICK",
    //       "COLAMBETTA",
    //       "COLE HAAN",
    //       "COLLEZIONE DI INES",
    //       "COLLONIL",
    //       "COLOMBO",
    //       "COLORADO JEANS",
    //       "COLORPLAY",
    //       "COLORS OF CALIFORNIA",
    //       "COMMA",
    //       "COMMA CASUAL IDENTITY",
    //       "COMPAGNIE DE CALIFORNIE",
    //       "COMPANIA FANTASTICA",
    //       "CONCEPT CLUB",
    //       "CONGUITOS",
    //       "CONHPOL",
    //       "CONSTRUE",
    //       "CONVER",
    //       "CONVERSE",
    //       "COOPER",
    //       "COP.COPINE",
    //       "CORINA",
    //       "CORNELIANI",
    //       "CORTIGIANI",
    //       "COSTUME NATIONAL",
    //       "COTE&CIEL",
    //       "COURA",
    //       "CO|TE",
    //       "CP COMPANY",
    //       "CRABRO",
    //       "CRESSI",
    //       "CRISTIAN LAY",
    //       "CROCS",
    //       "CROSBY",
    //       "CROWN MAGIC",
    //       "CRUCIANI",
    //       "CUBE CO",
    //       "CUBIC",
    //       "CUDGI",
    //       "CUPL?",
    //       "CUT & PRET",
    //       "CUT & PRET PLUS",
    //       "CVCover",
    //       "D'EXTERIOR",
    //       "D'ORANGE",
    //       "D. EXTERIOR",
    //       "D.MOLINA",
    //       "D?MINI",
    //       "DAKKEM",
    //       "DALI",
    //       "DALMINE",
    //       "DAMEROSE",
    //       "DAMIR DOMA",
    //       "DANIELE ALESSANDRINI",
    //       "DANIELLE",
    //       "DANIIL ANTSIFEROV",
    //       "DARIA BARDEEVA",
    //       "DAZE",
    //       "DE FONSECA",
    //       "DE PIETRI",
    //       "DEFACTO",
    //       "DEL GATTO",
    //       "DEPARE",
    //       "DEREK ROSE",
    //       "DERHY",
    //       "DESIGUAL",
    //       "DESTIN",
    //       "DIAMANTIQUE",
    //       "DIANE VON FURSTENBERG",
    //       "DIEGO M",
    //       "DIEGO VENTURINO",
    //       "DIESEL",
    //       "DIGEL",
    //       "DIM",
    //       "DINO RICCI",
    //       "DIRK BIKKEMBERGS",
    //       "DIRKJE",
    //       "DISETTA",
    //       "DIVISIBILE",
    //       "DJ DUTCHJEANS",
    //       "DJI",
    //       "DKNY",
    //       "DOCA",
    //       "DOLCE & GABBANA",
    //       "DOLCE GRACIA",
    //       "DOLCE&GABBANA",
    //       "DOM REBEL",
    //       "DONDUP",
    //       "DONMIAO",
    //       "DONNA LOKA",
    //       "DONNA MODA",
    //       "DOPPIO SEGNO",
    //       "DORIANI",
    //       "DOROTHEE SCHUMACHER",
    //       "DOUCAL`S",
    //       "DR MARTENS",
    //       "DR. MARTENS",
    //       "DROME",
    //       "DRYKORN",
    //       "DSQUARED2",
    //       "DU MONDE",
    //       "DUET.BY.ME",
    //       "DUMMI",
    //       "DUSTIN",
    //       "DUVETICA",
    //       "E-BOUND",
    //       "E.LEVY",
    //       "EA7",
    //       "EA7 EMPORIO ARMANI",
    //       "EASSPAULO",
    //       "EBENE",
    //       "ECCO",
    //       "ECHO OF HOLLYWOOD",
    //       "EDC",
    //       "EDUARD DRESSLER",
    //       "EDWIN",
    //       "EL CORTE INGLES KIDS",
    //       "ELCHE",
    //       "ELEGAMI",
    //       "ELENA IACHI",
    //       "ELENA MIRO",
    //       "ELEVENTY",
    //       "ELIE SAAB",
    //       "ELISA FANTI",
    //       "ELISABETH",
    //       "ELISABETTA FRANCHI",
    //       "ELLESSE",
    //       "ELSI",
    //       "EMDI",
    //       "EMKA FASHION",
    //       "EMME MARELLA",
    //       "EMPORIO ARMANI",
    //       "ENCHANTIMALS",
    //       "ENFASIS",
    //       "ENJOIN'",
    //       "ENZO",
    //       "EQUESTRIA GIRLS",
    //       "EREDA",
    //       "ERICKSON BEAMON",
    //       "ERMANNO ERMANNO SCERVINO",
    //       "ERMANNO FIRENZE",
    //       "ERMANNO SCERVINO",
    //       "ERMENEGILDO ZEGNA",
    //       "ESCAN",
    //       "ESPRIT",
    //       "ESPRIT CASUAL",
    //       "ESPRIT COLLECTION",
    //       "ESPRIT EDC",
    //       "ESSENTIALS BY STOCKMANN",
    //       "ESSENTIEL",
    //       "ESTYLE",
    //       "ETIENNE MARCELLE",
    //       "ETINCELLE",
    //       "ETNIES",
    //       "ETOILE DU MONDE",
    //       "ETON",
    //       "ETRO",
    //       "ETWOB",
    //       "EVANS",
    //       "EVER BE",
    //       "EVIGI",
    //       "EVIKA KIDS",
    //       "EVITA",
    //       "EVOLUTION",
    //       "EXCLAIM",
    //       "EXE'",
    //       "EXQUILY",
    //       "EXTASY",
    //       "El DANTES",
    //       "El FA MEI",
    //       "F.C. REAL BRISTOL",
    //       "F5",
    //       "FABI",
    //       "FABIANA FILIPPI",
    //       "FABIEN DE FERANTE",
    //       "FABIO RUSCONI",
    //       "FALKE",
    //       "FASHION WOMEN",
    //       "FAY",
    //       "FEDELI",
    //       "FEDERICA MORETTI",
    //       "FELINA",
    //       "FENDI",
    //       "FERRARI",
    //       "FERRE",
    //       "FERSINI",
    //       "FETICHE",
    //       "FILA",
    //       "FILODORO",
    //       "FINETTE",
    //       "FINN FLARE",
    //       "FINN LINE",
    //       "FIORI&SPINE",
    //       "FIORONI CASHMERE",
    //       "FISICO",
    //       "FLAVIO CASTELLANI",
    //       "FLG",
    //       "FLY",
    //       "FLYFOR",
    //       "FONTANELLI",
    //       "FOREVER UNIQUE",
    //       "FORNARINA",
    //       "FORTE&FRAGILE",
    //       "FRAAS",
    //       "FRACOMINA",
    //       "FRAME",
    //       "FRANCESCHETTI",
    //       "FRANCESCO DONNI",
    //       "FRANCO PARMEGGIANI",
    //       "FRANKIE MORELLO",
    //       "FRANSA",
    //       "FRATELLI ROSSETTI",
    //       "FRATELLI ROSSETTI ONE",
    //       "FRED PERRY",
    //       "FREE AGE",
    //       "FREEDOMDAY",
    //       "FREESTYLE",
    //       "FRETTE",
    //       "FRIDA",
    //       "FRIIS & COMPANY",
    //       "FROZEN",
    //       "FRYE",
    //       "FURLA",
    //       "FURLAND",
    //       "F_WD",
    //       "G&G",
    //       "G-STAR",
    //       "G.SEL",
    //       "GAI MATTIOLO",
    //       "GALLIANO",
    //       "GALVANNI",
    //       "GANNI",
    //       "GANT",
    //       "GAP",
    //       "GARDEN",
    //       "GARLAND",
    //       "GAS FOOTWEAR",
    //       "GAUDI",
    //       "GCDS",
    //       "GELSOMINO",
    //       "GENEVE",
    //       "GENTRYPORTOFINO",
    //       "GEORGE J. LOVE",
    //       "GEOX",
    //       "GERARD DAREL",
    //       "GERRY WEBER",
    //       "GERRY WEBER CASUAL",
    //       "GERRY WEBER EDITION",
    //       "GF FERRE'",
    //       "GHOUD",
    //       "GIA COUTURE",
    //       "GIA GIA",
    //       "GIANANTONIO A.PALADINI",
    //       "GIANCARLO PETRIGLIA",
    //       "GIANI FORTE",
    //       "GIANVITO ROSSI",
    //       "GIOIA",
    //       "GIOIA DELL’ACQUA",
    //       "GIORGIO ARMANI",
    //       "GIORGIO BRATO",
    //       "GIORGIO DI MARE",
    //       "GIORGIO FABIANI",
    //       "GIORGIO GRATI",
    //       "GIOSEPPO",
    //       "GIOTTO",
    //       "GIPSY CHIC",
    //       "GIRLHOOD",
    //       "GIUSEPPE ZANOTTI",
    //       "GLAMOROUS",
    //       "GLAMforever",
    //       "GLENFIELD",
    //       "GLORIA JEANS",
    //       "GLOSS",
    //       "GO-GO",
    //       "GOLDEN STAR",
    //       "GONE",
    //       "GOOD VIBES",
    //       "GOTTEX",
    //       "GRAMICCI",
    //       "GRAN  SASSO",
    //       "GRAND POMMES",
    //       "GRAND STYLE",
    //       "GREEN COAST",
    //       "GREENWICH POLO CLUB",
    //       "GRENDHA",
    //       "GREYMER",
    //       "GRIMALDIMARE",
    //       "GUESS",
    //       "GUESS BY MARCIANO",
    //       "GUESS JEANS",
    //       "GUIDO LA ROCCA",
    //       "GUIDO LOMBARDI",
    //       "GZ",
    //       "HAIDER ACKERMANN",
    //       "HALFBOY",
    //       "HAND PICKED",
    //       "HANDPICKED",
    //       "HAPPINESS SHOES",
    //       "HARMONT&BLAINE",
    //       "HAT YOU",
    //       "HATPARAD",
    //       "HAVIN",
    //       "HAYS",
    //       "HCS",
    //       "HEINE",
    //       "HELLY HANSEN",
    //       "HENRY BEGUELIN",
    //       "HERNO",
    //       "HERON PRESTON",
    //       "HESTREND",
    //       "HETTABRETZ",
    //       "HIGH",
    //       "HILTL",
    //       "HISTORY REPEATS",
    //       "HOBBS",
    //       "HOGAN",
    //       "HOLY CAFTAN",
    //       "HOMAND",
    //       "HOSS INTROPIA",
    //       "HOT WHEELS",
    //       "HUGO",
    //       "HUGO BOSS",
    //       "HUMMEL",
    //       "HUQ",
    //       "HYDROP",
    //       "H`D`S`N BARACCO",
    //       "IANA",
    //       "IBLUES",
    //       "ICE ICEBERG",
    //       "ICE PLAY",
    //       "ICEBERG",
    //       "ICEPEAK",
    //       "ICHI",
    //       "IDEAL",
    //       "IDO",
    //       "IENKI IENKI",
    //       "IKAROS",
    //       "ILENIA P.",
    //       "IMAC",
    //       "IMPERIAL",
    //       "INARIO",
    //       "INBLU",
    //       "INCITY",
    //       "INCOTEX",
    //       "INDIANA",
    //       "INDIGIRA",
    //       "INES MARECHAL",
    //       "INFLUENCE",
    //       "INNAMORE",
    //       "INNOCENT",
    //       "INUOVO",
    //       "INVERNI",
    //       "IPANEMA",
    //       "IPHORIA",
    //       "IRENEISGOOD",
    //       "IRONI",
    //       "ISABEL MARANT",
    //       "ISABEL QUEEN",
    //       "ISAIA",
    //       "ISLO ISABELLA LORUSSO",
    //       "ISOLEMAESTRE",
    //       "ISOTONER",
    //       "ITEMBLACK",
    //       "IVOLGA",
    //       "J BRAND",
    //       "JACK & JONES",
    //       "JACOB COHEN",
    //       "JACQUEMUS",
    //       "JALOE",
    //       "JANA",
    //       "JANEMOX by RIGHI JR",
    //       "JANESSA",
    //       "JANET SPORT",
    //       "JANIKO",
    //       "JASON MARKK",
    //       "JEANNOT",
    //       "JEFFREY CAMPBELL",
    //       "JENNEFFER",
    //       "JEREMY-HO",
    //       "JESSICA SIMPSON",
    //       "JESSICA WRIGHT",
    //       "JIL SANDER",
    //       "JILO'",
    //       "JIMMY CHOO",
    //       "JOE SUIS",
    //       "JOG DOG",
    //       "JOHN  SMEDLEY",
    //       "JOHN GALLIANO",
    //       "JOHN RICHMOND",
    //       "JOHN VARVATOS",
    //       "JOHNSTONS",
    //       "JONATHAN COREY",
    //       "JOSEPH",
    //       "JUICY COUTURE",
    //       "JULI TOO",
    //       "JUNIOR REPUBLIC",
    //       "JUS D'ORANGE",
    //       "JUS DE POMMES",
    //       "JUST CAVALLI",
    //       "JUST COUTURE",
    //       "JUSTFAB",
    //       "JUVIA",
    //       "JUVIS",
    //       "JW ANDERSON",
    //       "KAKADU",
    //       "KAMIK",
    //       "KANNA",
    //       "KAPPA",
    //       "KARANFIL",
    //       "KARL LAGERFELD",
    //       "KARL LAGERFELD PARIS",
    //       "KARL by KARL LAGERFELD",
    //       "KAROLINA",
    //       "KATY PERRY",
    //       "KEDDO",
    //       "KELLIS",
    //       "KENDALL&KYLIE",
    //       "KENZO",
    //       "KERRY",
    //       "KETI CHKHIKVADZE",
    //       "KHAITE",
    //       "KHRISJOY",
    //       "KING BOOTS",
    //       "KITON",
    //       "KIVAT",
    //       "KLIMINI",
    //       "KN COLLECTION",
    //       "KOKO NOKO",
    //       "KRUZO",
    //       "KSUBI",
    //       "KUNERT",
    //       "KURT GEIGER",
    //       "L.B.M. 1911",
    //       "L.DAY",
    //       "L.O.L. SURPRISE!",
    //       "LA BOTTINE SOURIANTE",
    //       "LA CITY",
    //       "LA DARIQUE",
    //       "LA GATTA",
    //       "LA GRANDEZZA",
    //       "LA MIA PERLA",
    //       "LA PERLA",
    //       "LA PINTA",
    //       "LA STRADA",
    //       "LAB MILANO",
    //       "LABOUR",
    //       "LACEYS LONDON",
    //       "LACOSTE",
    //       "LAFFINELY",
    //       "LAIK",
    //       "LAKE",
    //       "LALU",
    //       "LAMALIBOO",
    //       "LAMANIA",
    //       "LAMBERTO LOSANI",
    //       "LANCASTER",
    //       "LANCEL",
    //       "LARDINI",
    //       "LAROOM",
    //       "LASESSOR",
    //       "LASSIE",
    //       "LAUR?N",
    //       "LAURA BIAGIOTTI",
    //       "LAURA SCOTT",
    //       "LAUREL",
    //       "LAUREN RALPH LAUREN",
    //       "LAURENCE DACADE",
    //       "LE COQ SPORTIF",
    //       "LE SILLA",
    //       "LE TRICOT PERUGIA",
    //       "LECOMTE",
    //       "LENA MILAN",
    //       "LERRE",
    //       "LERROS",
    //       "LES ARCHIVES",
    //       "LES PETITES BOMBES",
    //       "LES VENUES",
    //       "LET,S",
    //       "LEVI&APOS;S",
    //       "LEVI'S",
    //       "LEYA",
    //       "LIBERTINE-LIBERTINE",
    //       "LIFAMOSSO",
    //       "LIKE YANA",
    //       "LILIMILL",
    //       "LIMITATO",
    //       "LINDBERGH",
    //       "LINO MORANO",
    //       "LION OF PORCHES",
    //       "LIU JO",
    //       "LIU JO MILANO",
    //       "LIU •JO",
    //       "LIU •JO JEANS",
    //       "LNB",
    //       "LOEWE",
    //       "LOIZA by PATRIZIA PEPE",
    //       "LOLA CRUZ",
    //       "LOLOCLO",
    //       "LORELLA SIGNORINO",
    //       "LORENA ANTONIAZZI",
    //       "LORENZO MARI",
    //       "LORICCI",
    //       "LOSAN",
    //       "LOST INK.",
    //       "LOST&FOUND",
    //       "LOTTINI",
    //       "LOVE & MONEY",
    //       "LOVE CASHMERE",
    //       "LOVE MOSCHINO",
    //       "LOVE REPUBLIC",
    //       "LOVE STORIES",
    //       "LOVEBIRDS",
    //       "LUBIAM",
    //       "LUCIANO BARBERA",
    //       "LUCKY LAND",
    //       "LUHTA",
    //       "LUIGI BORRELLI",
    //       "LUISA SPAGNOLI",
    //       "L’ADORE",
    //       "M.V. MAGLIERIA VENETA",
    //       "MADA-EMME",
    //       "MADE FOR LOVING",
    //       "MADELEINE",
    //       "MADELLA",
    //       "MADEMOISELLE CHI CHI",
    //       "MAGRIT",
    //       "MAHARISHI",
    //       "MAISON 9 PARIS",
    //       "MAISON CO.GO",
    //       "MAISON ESPIN",
    //       "MAISON MARGIELA",
    //       "MAKFINE",
    //       "MAKFLY",
    //       "MALA MATI",
    //       "MALIBU",
    //       "MALIEN",
    //       "MALINA BY АНДЕРСЕН",
    //       "MALO",
    //       "MALVIN",
    //       "MANDELLI",
    //       "MANGO",
    //       "MANILA GRACE",
    //       "MANOUSH",
    //       "MANTU",
    //       "MANZONI 24",
    //       "MARC & ANDRE",
    //       "MARC CAIN",
    //       "MARC ELLIS",
    //       "MARC O&APOS;POLO",
    //       "MARC O&APOS;POLO DENIM",
    //       "MARC&ANDRE",
    //       "MARCELO BURLON",
    //       "MARCO BOLOGNA",
    //       "MARCO BONNE`",
    //       "MARCO DI RADI",
    //       "MARCO PESCAROLO",
    //       "MARCO TREDI",
    //       "MARCO VANOLI",
    //       "MARE ANDI",
    //       "MARIA GRAZIA SEVERI",
    //       "MARIAN",
    //       "MARIANNE",
    //       "MARICHUELL",
    //       "MARIE COLLET",
    //       "MARIMAY",
    //       "MARINA YACHTING",
    //       "MARIO BRUNI",
    //       "MARK LURE",
    //       "MARKO",
    //       "MARKS & SPENCER",
    //       "MARKUS LUPFER",
    //       "MARMALATO",
    //       "MARNI",
    //       "MARNIS ETROIS",
    //       "MARTIN PESCATORE",
    //       "MARVELIS",
    //       "MARYPAZ",
    //       "MASSIMO DUTTI",
    //       "MASSIMO SANTINI",
    //       "MASSIMO SFORZA",
    //       "MASTER-PIECE",
    //       "MASTERPEACE",
    //       "MATERIA PRIMA by GOFFREDO FANTINI",
    //       "MAURIZIO",
    //       "MAX MARA",
    //       "MAX&MOI",
    //       "MAXIMO",
    //       "MAYORAL",
    //       "MC2 SAINT BARTH",
    //       "MEDANI BAGS",
    //       "MEIMEU",
    //       "MELANIA",
    //       "MELISSA",
    //       "MELISSA ODABASH",
    //       "MELLISA",
    //       "MELROSE",
    //       "MEMBERS ONLY",
    //       "MET",
    //       "METRIC",
    //       "METROPOLPOLIS",
    //       "MEXX",
    //       "MICHAEL KORS",
    //       "MICHAEL MICHAEL KORS",
    //       "MIDGARD",
    //       "MIGURA",
    //       "MIKAEL",
    //       "MILANA",
    //       "MILANIKA",
    //       "MINELLI",
    //       "MINI RODINI",
    //       "MINNIE MOUSE",
    //       "MINOTI",
    //       "MISS MISS",
    //       "MISS ROBERTA",
    //       "MISS SELFRIDGE",
    //       "MISS SIXTY",
    //       "MISSI LONDON",
    //       "MISSONI",
    //       "MIXFEEL",
    //       "MIXMIX",
    //       "MIZUNO",
    //       "MJS",
    //       "MM6",
    //       "MM6 Maison Margiela",
    //       "MODA GY",
    //       "MODA di CHIARA",
    //       "MODEKO",
    //       "MOEVA",
    //       "MOHITO",
    //       "MOLO",
    //       "MON AMI",
    //       "MONCLER",
    //       "MONDIGO",
    //       "MONS&ORRO",
    //       "MONTECORE",
    //       "MONTEVERDI",
    //       "MONTON",
    //       "MOON RIVER",
    //       "MOORER",
    //       "MORE&MORE",
    //       "MORESCHI",
    //       "MORGAN",
    //       "MOSAIC",
    //       "MOSCHINO",
    //       "MOSCHINO Love",
    //       "MOTHER",
    //       "MUM OF SIX",
    //       "MUM OF SIX FOR СТОКМАНН",
    //       "MURSU",
    //       "MUSE ME",
    //       "MY LITTLE PONY",
    //       "MYTWIN",
    //       "NAME IT",
    //       "NANA BAILA",
    //       "NANDO MUZI",
    //       "NANUSHKA",
    //       "NAPAPIJRI",
    //       "NAPOLEONERBA",
    //       "NATAYAKIM",
    //       "NAUMI",
    //       "NEIL BARRETT",
    //       "NERO GIARDINI",
    //       "NERO SU BIANCO",
    //       "NEW BALANCE",
    //       "NICOLE OLIVIER",
    //       "NIKE",
    //       "NILA NILA",
    //       "NIMA",
    //       "NINA RICCI",
    //       "NISSA",
    //       "NIWEILE",
    //       "NO LIMITS NO WAY",
    //       "NOA",
    //       "NOBBARO",
    //       "NOLO",
    //       "NOOM",
    //       "NOOM LOUNGEWEAR",
    //       "NORDMAN",
    //       "NORKA",
    //       "NORMA J. BAKER",
    //       "NOT SHY",
    //       "NOTO KIDS",
    //       "NUKUTAVAKE",
    //       "NicClub",
    //       "No21",
    //       "OASIS",
    //       "OBJECT COLLECTORS",
    //       "OCHNIK",
    //       "ODRI",
    //       "ODRI MIO",
    //       "OFF-WHITE",
    //       "OLDOS",
    //       "OLGUN ORKUN",
    //       "OLO",
    //       "OLVI`S",
    //       "ON",
    //       "ONE X ONE TEASPOON",
    //       "ONLY",
    //       "ONLY & SONS",
    //       "OPENING CEREMONY",
    //       "ORIGINAL MARINES",
    //       "ORIGINAL PENGUIN",
    //       "ORLA KIELY",
    //       "OROSCURO",
    //       "OSEY",
    //       "OSHKOSH B&APOS;GOSH",
    //       "OUTFITTERS NATION",
    //       "OVS",
    //       "O`SHADE",
    //       "P.A.R.O.S.H.",
    //       "PACO RABANNE",
    //       "PAIGE",
    //       "PAKERSON",
    //       "PAL ZILERI",
    //       "PALM ANGELS",
    //       "PANICALE",
    //       "PANTALONI TORINO",
    //       "PANTOLETTI",
    //       "PAOLA FERRI BY ALBA MODA",
    //       "PAOLA RAY",
    //       "PAOLO CONTE",
    //       "PARAJUMPERS",
    //       "PARIS TEXAS",
    //       "PASHMERE",
    //       "PASSIONI",
    //       "PATRIZIA DINI",
    //       "PATRIZIA PEPE",
    //       "PATROL",
    //       "PAUL & JOE SISTER",
    //       "PAUL & SHARK",
    //       "PAUL SMITH",
    //       "PEACEFUL HOOLIGAN",
    //       "PELLETTIERI DI PARMA",
    //       "PENNYBLACK",
    //       "PEOPLE",
    //       "PEPE JEANS",
    //       "PEPEROSA",
    //       "PER TE",
    //       "PERSEVERANCE LONDON",
    //       "PERSONA BY MARINA RINALDI",
    //       "PERTINI",
    //       "PESERICO",
    //       "PETER FLOWERS",
    //       "PETER KAISER",
    //       "PETITES",
    //       "PHASE EIGHT",
    //       "PHILIPP PLEIN",
    //       "PHILIPPE MATIGNON",
    //       "PHILIPPE MODEL",
    //       "PHILIPPE MODEL PARIS",
    //       "PHILLIP LIM",
    //       "PHILOSOPHY DI LORENZO SERAFINI",
    //       "PIACENZA",
    //       "PIAZZA ITALIA",
    //       "PICCIONE.PICCIONE",
    //       "PIERRE CARDIN",
    //       "PINACCI",
    //       "PINKO",
    //       "PIP STUDIO",
    //       "PITTI",
    //       "PLAYGIRL",
    //       "PLAYTODAY",
    //       "PLEIN SPORT",
    //       "POKEMAOKE",
    //       "POLLINI",
    //       "POLO RALPH LAUREN",
    //       "PORTS 1961",
    //       "POUSTOVIT",
    //       "PRADA",
    //       "PRATIVERDI",
    //       "PREMIATA",
    //       "PRIMADONNA",
    //       "PRIMO EMPORIO",
    //       "PROENZA SCHOULER",
    //       "PTPT",
    //       "PULKA",
    //       "PUMA",
    //       "PUR PUR",
    //       "PURA L?PEZ",
    //       "QUEEN VIVI",
    //       "QUEENIE",
    //       "QUIKSILVER",
    //       "QUODLIBET",
    //       "R.J.BROWN",
    //       "RABE",
    //       "RACHEL ZOE",
    //       "RADEKS",
    //       "RAFFAELA D'ANGELO",
    //       "RAG AND BONE",
    //       "RAINBOW",
    //       "RALF RINGER",
    //       "RALPH LAUREN",
    //       "RAS",
    //       "RASARIO",
    //       "RAXMAX",
    //       "RAY-BAN",
    //       "RE VERA",
    //       "REEBOK",
    //       "REEBOK VB",
    //       "REEM ACRA",
    //       "REGATTA",
    //       "REIMA",
    //       "RELAX MODE",
    //       "RELIGION",
    //       "RENAISSANCE",
    //       "RENDA",
    //       "RENE CAOVILLA",
    //       "REPLAY",
    //       "REPORTER YOUNG",
    //       "RHEA COSTA",
    //       "RHS",
    //       "RICHARD J BROWN",
    //       "RICHARD J. BROWN",
    //       "RICHMOND",
    //       "RICHWEAR",
    //       "RICK CARDONA",
    //       "RICK OWENS",
    //       "RIDLSTEP",
    //       "RILORACE",
    //       "RINASCIMENTO",
    //       "RINDI",
    //       "RIO FIORE",
    //       "RIP CURL",
    //       "RITRATTI",
    //       "RIVER ISLAND",
    //       "RIVIERA",
    //       "ROBE LEGERE",
    //       "ROBERTO BOTELLA",
    //       "ROBERTO CAVALLI",
    //       "ROBERTO ROSSI",
    //       "ROCCOBAROCCO",
    //       "ROCHAS",
    //       "RODO",
    //       "ROECKL",
    //       "ROLAND MOURET",
    //       "ROSAMUNDA",
    //       "ROSANTICA",
    //       "ROSE CORVINA",
    //       "ROSEVILLE",
    //       "ROSY PELUSO",
    //       "ROTA",
    //       "ROZIECORSETS",
    //       "RUCO LINE",
    //       "RUSHEV",
    //       "S. OLIVER",
    //       "S.FERRAGAMO",
    //       "S.OLIVER",
    //       "SABRINA SCALA",
    //       "SAIJUN",
    //       "SAIL 1780",
    //       "SAINT LAURENT",
    //       "SALONI",
    //       "SAMANTHA SUNG",
    //       "SAMOON",
    //       "SAMSOE&SAMSOE",
    //       "SAND",
    //       "SANDQVIST",
    //       "SANETTA",
    //       "SANINO NAPOLI",
    //       "SANTONI",
    //       "SARA ROKA",
    //       "SASHA BERG",
    //       "SASHAVERSE",
    //       "SASSOFONO",
    //       "SAUCONY",
    //       "SAVAGE",
    //       "SAYOTA",
    //       "SCARLETT POPPIES",
    //       "SCHIATTI",
    //       "SCHIESSER",
    //       "SCHMUDDELWEDDA",
    //       "SCHUTZ",
    //       "SCISSOR SCRIPTOR",
    //       "SCOTCH & SODA",
    //       "SCRAMBLED EGO",
    //       "SEAFOLLY",
    //       "SEBASTIAN",
    //       "SEE BY CHLOE",
    //       "SELA",
    //       "SELECTED",
    //       "SELECTED FEMME",
    //       "SELF-PORTRAIT",
    //       "SELFIE",
    //       "SEMILLA",
    //       "SENSO ZIA",
    //       "SERAFINI ETOILE",
    //       "SERAFINI TIMES",
    //       "SERAPHIN",
    //       "SERGIO ROSSI",
    //       "SERGIO TODZI",
    //       "SERMONETA",
    //       "SERMONETA GLOVES",
    //       "SESSUN",
    //       "SHAMILU",
    //       "SHATU",
    //       "SHEPHERD",
    //       "SHI TINO",
    //       "SHINE ORIGINAL",
    //       "SILMAR",
    //       "SILOU",
    //       "SILVANO BIAGINI",
    //       "SILVER SPOON",
    //       "SILVER SPOON CEREMONY",
    //       "SILVER SPOON LIFE",
    //       "SILVIA EXCLUSIVE COLLECTION",
    //       "SILVIAN HEACH",
    //       "SIMON&SCOTT",
    //       "SIMONETTA RAVIZZA",
    //       "SINLY",
    //       "SJLNI",
    //       "SJYP",
    //       "SKINY",
    //       "SLAZENGER",
    //       "SMALTO",
    //       "SMILE OF MILADY",
    //       "SOFFI SALITA TREND",
    //       "SOLEMATE",
    //       "SOLO SOPRANI",
    //       "SONIA FORTUNA",
    //       "SONIA RYKIEL",
    //       "SOPHNET.",
    //       "SOREL",
    //       "SPALDING",
    //       "SPARKLING",
    //       "SPAZIOMODA",
    //       "SPOON",
    //       "SPRING WAY",
    //       "SPRINGWAY",
    //       "SPUR",
    //       "ST. STUDIO",
    //       "ST.BARTH",
    //       "STEFANEL",
    //       "STEFANO BELLINI",
    //       "STEFANO RICCI",
    //       "STEFFEN SCHRAUT",
    //       "STELLA JEAN",
    //       "STELLA MCCARTNEY",
    //       "STELLA MCCARTNEY SPORT",
    //       "STELLA McCARTNEY",
    //       "STELLAR",
    //       "STEP BY STEP",
    //       "STEPHAN",
    //       "STESSO",
    //       "STETS",
    //       "STETSON",
    //       "STEVE MADDEN",
    //       "STEVIE MAY",
    //       "STILE LATINO",
    //       "STITCH'S",
    //       "STOKTON",
    //       "STRATEGIA",
    //       "STRELLSON",
    //       "STROBBS",
    //       "STUART WEITZMAN",
    //       "SUGARHILL BOUTIQUE",
    //       "SUMMERGIRL",
    //       "SUNCOO",
    //       "SUPER MODE",
    //       "SUPERDRY",
    //       "SUPERFINE",
    //       "SUPERFIT",
    //       "SUPERTRASH",
    //       "SUSIMODA",
    //       "SVETSKI",
    //       "SVEVO",
    //       "SWEET SHOES",
    //       "SWEEWE",
    //       "SWEEWE PARIS",
    //       "SYMETRIE",
    //       "S`COOL",
    //       "T.TACCARDI",
    //       "TACCO",
    //       "TADASHI",
    //       "TAGLIATORE",
    //       "TAIFUN",
    //       "TAK.ORI",
    //       "TALLY WEIJL",
    //       "TAMARIS",
    //       "TARDINI",
    //       "TED BAKER LONDON",
    //       "TEE SPACE",
    //       "TEREKHOV",
    //       "TEREKHOV GIRL",
    //       "TERESA TARDIA",
    //       "TERVOLINA",
    //       "TESORO",
    //       "THANKS4LIFE",
    //       "THE FIFTH",
    //       "THE KOOPLES",
    //       "THE LAB",
    //       "THE NORTH FACE",
    //       "THE ROW",
    //       "THOMAS BALDWIN",
    //       "TIFFI",
    //       "TIMBERLAND",
    //       "TIMEX",
    //       "TOD`S",
    //       "TOM FARR",
    //       "TOM FORD",
    //       "TOM TAILOR",
    //       "TOM and JERRY",
    //       "TOMBOLINI",
    //       "TOMMY HILFIGER",
    //       "TOMMY JEANS",
    //       "TOMMY JEANS BY TOMMY HILFIGER",
    //       "TONET",
    //       "TOP OR by JENNY & CO",
    //       "TOP SECRET",
    //       "TOPSHOP",
    //       "TORRE VALLEY",
    //       "TOSCA BLU",
    //       "TOSCA BLU SHOES",
    //       "TOSKVA",
    //       "TOTEM",
    //       "TRAMAROSSA",
    //       "TRASPARENZE",
    //       "TRASPARENZINE",
    //       "TRASTA",
    //       "TRESOPHIE",
    //       "TRESPASS",
    //       "TROLL",
    //       "TRUSSARDI JEANS",
    //       "TULIPANO",
    //       "TWIN SET",
    //       "TWINSET",
    //       "TWINSET / LE COUER",
    //       "TWINSET / MY TWIN",
    //       "TWINSET / U&B",
    //       "TWINSET Milano",
    //       "U.S. POLO ASSN.",
    //       "UGG",
    //       "UGG AUSTRALIA",
    //       "UNDER ARMOUR",
    //       "UNGE LARSON",
    //       "UNIFORM EXPERIMENT",
    //       "UNIQLO",
    //       "UNISA",
    //       "UNITED COLORS OF BENETTON",
    //       "UNITED NUDE",
    //       "UNITEKS",
    //       "UNQ",
    //       "URBAN SUN",
    //       "VABENE",
    //       "VAGABOND",
    //       "VALENTINO",
    //       "VALENTINO GARAVANI",
    //       "VALENTINO RED",
    //       "VALKIRIA",
    //       "VALLEY",
    //       "VALORI",
    //       "VAN LAACK",
    //       "VANS",
    //       "VARESE",
    //       "VASSA&CO",
    //       "VASSA&CO PIN CODE",
    //       "VENCA",
    //       "VERA MONT",
    //       "VERA VICTORIA VITO",
    //       "VERO MODA",
    //       "VERSACE",
    //       "VERSACE 19.69",
    //       "VERSACE COLLECTION",
    //       "VERSACE JEANS",
    //       "VERSACE JEANS COUTURE",
    //       "VEZAVENA",
    //       "VIA CAPPELLA",
    //       "VIA TORRIANI 88",
    //       "VIC MATIE",
    //       "VIC MATIE'",
    //       "VICINI",
    //       "VICINI TAPEET",
    //       "VICTORIA BECKHAM",
    //       "VICTORIA SCARLETT",
    //       "VIKA GAZINSKAYA",
    //       "VIKA SMOLYANITSKAYA",
    //       "VIKING",
    //       "VILA",
    //       "VILATTE",
    //       "VILEBREQUIN",
    //       "VINCE CAMUTO",
    //       "VIOLANTI",
    //       "VIONNET",
    //       "VIS-A-VIS",
    //       "VITA RICCA",
    //       "VITACCI",
    //       "VIVA LA DONNA",
    //       "VIVANCE COLLECTION",
    //       "VIVETTA",
    //       "VIVI",
    //       "VIVIAN ROYAL",
    //       "VOGUE",
    //       "VOILE BLANCHE",
    //       "VUALL",
    //       "W.GIBBS",
    //       "WAG CONCEPT",
    //       "WAREHOUSE",
    //       "WEGENER",
    //       "WHISTLES",
    //       "WILD FOX",
    //       "WILDFOX",
    //       "WILLIAM SHARP",
    //       "WILMAR",
    //       "WILSON LEATHER",
    //       "WINDSOR",
    //       "WINZOR",
    //       "WISH CANDLE PARIS",
    //       "WODEN",
    //       "WONDERS",
    //       "WOOL&COTTON",
    //       "WOOLRICH",
    //       "WRANGLER",
    //       "WS",
    //       "WS SHOES",
    //       "X'cluSIve",
    //       "XTI",
    //       "Y-3",
    //       "Y.A.S",
    //       "Y.O.U.",
    //       "YAGEMILAN",
    //       "YAKUBOWITCH",
    //       "YUKA",
    //       "YVES SALOMON",
    //       "YZY",
    //       "Z ZEGNA",
    //       "ZADIG & VOLTAIRE",
    //       "ZADIG&VOLTAIRE",
    //       "ZANETTI 1965",
    //       "ZARA",
    //       "ZASPORT",
    //       "ZAZA",
    //       "ZILANLIYA",
    //       "ZILLI",
    //       "ZIMMERMANN",
    //       "ZUMITA",
    //       "iBlues",
    //       "АКОС",
    //       "АНДЕРСЕН",
    //       "БЕМБI",
    //       "ВТОРОЙ МЕХОВОЙ",
    //       "ДЕРЕВЬЯ",
    //       "ДЮНА",
    //       "ЗАР-СТИЛЬ",
    //       "КОРОЛЕВА",
    //       "МИНЬОНЫ",
    //       "РОССИЙСКИЙ ТРИКОТАЖ",
    //       "САЗ",
    //       "ТВОЕ",
    //       "ТРОЛЛИ",
    //       "ЭВАНТЮЭЛЬ",
    //       null
    //     ],
    //     "sizes": [
    //       "OS",
    //       "XXXS",
    //       "XXS",
    //       "XS",
    //       "S",
    //       "S/M",
    //       "M",
    //       "M/L",
    //       "L",
    //       "XL",
    //       "XXL",
    //       "36R",
    //       "XXXL",
    //       "XXXXL",
    //       "75D",
    //       "75C",
    //       "80C",
    //       "80D",
    //       "6Y",
    //       "8Y",
    //       "10Y",
    //       "12Y",
    //       "38R",
    //       "6.5",
    //       "16",
    //       "23",
    //       "24",
    //       "25",
    //       "26",
    //       "27",
    //       "28",
    //       "29",
    //       "30",
    //       "31",
    //       "32",
    //       "33",
    //       "34",
    //       "34.5",
    //       "35",
    //       "35.5",
    //       "36",
    //       "36.5",
    //       "37",
    //       "37.5",
    //       "38",
    //       "38.5",
    //       "39",
    //       "39.5",
    //       "40",
    //       "40.5",
    //       "41",
    //       "41.5",
    //       "42",
    //       "42.5",
    //       "43",
    //       "43.5",
    //       "44",
    //       "44.5",
    //       "45",
    //       "45.5",
    //       "46",
    //       "47",
    //       "48",
    //       "50",
    //       "52",
    //       "54",
    //       "55",
    //       "56",
    //       "57",
    //       "58",
    //       "59",
    //       "60",
    //       "61",
    //       "62",
    //       "63",
    //       "64",
    //       "66",
    //       "70",
    //       "75",
    //       "80",
    //       "85",
    //       "90",
    //       "92",
    //       "95",
    //       "100",
    //       "104",
    //       "105",
    //       "110",
    //       "115",
    //       "116",
    //       "120",
    //       "122",
    //       "125",
    //       "128",
    //       "130",
    //       "134",
    //       "135",
    //       "140",
    //       "146",
    //       "152",
    //       "158",
    //       "164"
    //     ],
    //     "_type": {
    //       "clothes": [
    //         "Casual",
    //         "А-силуэт",
    //         "Анораки",
    //         "Блузки",
    //         "Блузы",
    //         "Блузы и рубашки",
    //         "Блузы с принтом",
    //         "Боди",
    //         "Бойфренды",
    //         "Бомберы",
    //         "Брюки",
    //         "Брюки зауженные",
    //         "Брюки и шорты",
    //         "Брюки и шорты для дома",
    //         "Брюки карго",
    //         "Брюки классические",
    //         "Брюки кожаные",
    //         "Брюки повседневные",
    //         "Брюки прямые",
    //         "Брюки с высокой посадкой",
    //         "Брюки свободный крой",
    //         "Брюки слаксы",
    //         "Брюки со стандартной посадкой",
    //         "Брюки спортивные",
    //         "Брюки укороченные",
    //         "Брюки утепленные",
    //         "Брюки хлопковые",
    //         "Брюки чиносы",
    //         "Брюки широкие",
    //         "Брюки-карго",
    //         "Бюстгальтеры",
    //         "В клетку",
    //         "Верхняя одежда",
    //         "Ветровки",
    //         "Водолазки",
    //         "Водолазки длинные",
    //         "Водолазки однотонные",
    //         "Вязаные",
    //         "Галстуки и бабочки",
    //         "Джеггинсы",
    //         "Джемперы",
    //         "Джинсы",
    //         "Джинсы бойфренды",
    //         "Джинсы высокая посадка",
    //         "Джинсы зауженные",
    //         "Джинсы на молнии",
    //         "Джинсы прямые",
    //         "Джинсы скинни",
    //         "Джинсы укороченные",
    //         "Джинсы широкие",
    //         "Джинсы-момы",
    //         "Джоггеры",
    //         "Для девочек",
    //         "Для мальчиков",
    //         "Домашние брюки",
    //         "Домашние шорты",
    //         "Домашняя одежда",
    //         "Жакеты",
    //         "Жакеты и пиджаки",
    //         "Жилеты",
    //         "Жилеты джинсовые",
    //         "Жилеты классические",
    //         "Жилеты меховые",
    //         "Жилеты стеганые",
    //         "Жилеты стёганые",
    //         "Жилеты трикотажные",
    //         "Жилеты удлиненные",
    //         "Жилеты утепленные",
    //         "Зауженные",
    //         "Зимняя",
    //         "Кардиганы",
    //         "Кардиганы длинные",
    //         "Кардиганы на молнии",
    //         "Кардиганы на пуговицах",
    //         "Кардиганы оверсайз",
    //         "Кепки",
    //         "Классические",
    //         "Клеш",
    //         "Клёш",
    //         "Кожаные",
    //         "Комбинезоны",
    //         "Комбинезоны демисезонные",
    //         "Комбинезоны джинсовые",
    //         "Комбинезоны с брюками",
    //         "Комбинезоны с шортами",
    //         "Корсеты",
    //         "Костюмы",
    //         "Костюмы и жакеты",
    //         "Костюмы классические",
    //         "Костюмы с брюками",
    //         "Костюмы с юбкой",
    //         "Костюмы спортивные",
    //         "Купальники",
    //         "Купальники и пляжная одежда",
    //         "Куртки",
    //         "Куртки демисезонные",
    //         "Куртки джинсовые",
    //         "Куртки зимние",
    //         "Куртки кожаные",
    //         "Куртки меховые",
    //         "Куртки оверсайз",
    //         "Куртки укороченные",
    //         "Кюлоты",
    //         "Леггинсы",
    //         "Леггинсы спортивные",
    //         "Легинсы",
    //         "Легинсы утепленные",
    //         "Лонгсливы",
    //         "Лосины спортивные",
    //         "Майки",
    //         "Макси",
    //         "Миди",
    //         "Мини",
    //         "Мягкие",
    //         "Накидки",
    //         "Нижнее белье",
    //         "Нижнее белье и шорты",
    //         "Новинки",
    //         "Носки",
    //         "Носки, колготки, гольфы",
    //         "Ночные сорочки",
    //         "Одежда",
    //         "Одежда для горнолыжного спорта",
    //         "Одежда для дома и сна",
    //         "Одежда для спорта",
    //         "Олимпийки",
    //         "Осенняя",
    //         "Офисные",
    //         "Пальто",
    //         "Пальто демисезонные",
    //         "Пальто драповые",
    //         "Пальто однотонные",
    //         "Панамы",
    //         "Парео",
    //         "Парки",
    //         "Парки с капюшоном",
    //         "Парки удлиненные",
    //         "Пеналы",
    //         "Пеньюары",
    //         "Пиджаки",
    //         "Пиджаки на пуговицах",
    //         "Пиджаки под джинсы",
    //         "Пижамы",
    //         "Пижамы и сорочки",
    //         "Плавки",
    //         "Платья",
    //         "Платья без рукавов",
    //         "Платья вечерние",
    //         "Платья джинсовые",
    //         "Платья и сарафаны",
    //         "Платья и юбки",
    //         "Платья коктейльные",
    //         "Платья летние",
    //         "Платья офисные",
    //         "Платья пляжные",
    //         "Платья повседневные",
    //         "Платья с длинным рукавом",
    //         "Платья с коротким рукавом",
    //         "Платья с открытыми плечами",
    //         "Платья-рубашки",
    //         "Плащи",
    //         "Плащи демисезонные",
    //         "Плащи и тренчи",
    //         "Поло",
    //         "Поло однотонные",
    //         "Поло с длинным рукавом",
    //         "Поло с коротким рукавом",
    //         "Поло с принтом",
    //         "Пончо",
    //         "Пончо и накидки",
    //         "Последний размер",
    //         "Приталенные",
    //         "Пуловеры",
    //         "Пуловеры зимние",
    //         "Пуловеры на молнии",
    //         "Пуловеры с v-образным вырезом",
    //         "Пуловеры с капюшоном",
    //         "Пуловеры с круглым вырезом",
    //         "Пуховики",
    //         "Пуховики с капюшоном",
    //         "Пуховики удлиненные",
    //         "Пышные",
    //         "Разноцветные",
    //         "Рубашки",
    //         "Рубашки джинсовые",
    //         "Рубашки и сорочки",
    //         "Рубашки классические",
    //         "Рубашки оверсайз",
    //         "Рубашки приталенные",
    //         "Рубашки с длинным рукавом",
    //         "Рубашки с коротким рукавом",
    //         "Рубашки удлиненные",
    //         "Рубашки-поло",
    //         "С высокой талией",
    //         "С защипами",
    //         "С низкой посадкой",
    //         "С юбкой",
    //         "Сарафаны",
    //         "Свитеры",
    //         "Свитеры с длинным рукавом",
    //         "Свитшоты",
    //         "Свитшоты оверсайз",
    //         "Свитшоты с принтом",
    //         "Свитшоты удлиненные",
    //         "Скинни",
    //         "Смокинги",
    //         "Со стандартной талией",
    //         "Сорочки и рубашки длинные",
    //         "Сорочки и рубашки оверсайз",
    //         "Сорочки и рубашки с длинным рукавом",
    //         "Спортивная одежда",
    //         "Спортивные",
    //         "Спортивные костюмы",
    //         "Тайтсы",
    //         "Термобелье",
    //         "Толстовки",
    //         "Толстовки длинные",
    //         "Толстовки и свитшоты",
    //         "Толстовки оверсайз",
    //         "Толстовки однотонные",
    //         "Толстовки с капюшоном",
    //         "Толстовки утепленные",
    //         "Топы",
    //         "Топы и майки",
    //         "Топы спортивные",
    //         "Трапеции",
    //         "Тренчи и плащи",
    //         "Трикотажные",
    //         "Трусы",
    //         "Туники",
    //         "Туники в стиле casual",
    //         "Туники на пуговицах",
    //         "Туники-рубашки",
    //         "Утепленные жилеты",
    //         "Футболки",
    //         "Футболки Поло",
    //         "Футболки в стиле casual",
    //         "Футболки длинные",
    //         "Футболки и майки",
    //         "Футболки оверсайз",
    //         "Футболки однотонные",
    //         "Футболки с коротким рукавом",
    //         "Футболки с принтом",
    //         "Футболки спортивные",
    //         "Футболки узкие",
    //         "Хаки",
    //         "Халаты",
    //         "Худи",
    //         "Худи длинные",
    //         "Худи оверсайз",
    //         "Худи утепленные",
    //         "Чиносы",
    //         "Чулки, носки, колготки",
    //         "Шапки",
    //         "Шерстяные",
    //         "Школьная одежда",
    //         "Шорты",
    //         "Шорты джинсовые",
    //         "Шорты и брюки для пляжа",
    //         "Шорты повседневные",
    //         "Шорты спортивные",
    //         "Шубы и дубленки",
    //         "Юбки",
    //         "Юбки без рисунка",
    //         "Юбки годе",
    //         "Юбки джинсовые",
    //         "Юбки кожаные",
    //         "Юбки макси",
    //         "Юбки миди",
    //         "Юбки мини",
    //         "Юбки плиссированные",
    //         "Юбки прямые",
    //         "Юбки узкие",
    //         "Юбки широкие",
    //         "Юбки-карандаш"
    //       ],
    //       "shoes": [
    //         "Балетки",
    //         "Балетки кожаные",
    //         "Босоножки",
    //         "Босоножки на каблуке",
    //         "Босоножки на танкетке",
    //         "Босоножки с ремешками",
    //         "Ботильоны",
    //         "Ботинки",
    //         "Ботинки без каблука",
    //         "Ботинки кожаные",
    //         "Ботинки повседневные",
    //         "Ботфорты",
    //         "Броги",
    //         "Городские",
    //         "Дезерты",
    //         "Демисезонная",
    //         "Дерби",
    //         "Домашняя обувь",
    //         "Дутики",
    //         "Женская обувь",
    //         "Зимняя",
    //         "Кеды",
    //         "Кеды в стиле casual",
    //         "Кеды легкие",
    //         "Кеды на шнурках",
    //         "Классические",
    //         "Кроссовки",
    //         "Кроссовки в стиле casual",
    //         "Кроссовки замшевые",
    //         "Лоферы",
    //         "Мокасины",
    //         "Монки",
    //         "Мужская обувь",
    //         "Мюли",
    //         "На высоком каблуке",
    //         "На каблуке",
    //         "На платформе",
    //         "На шпильке",
    //         "Новые поступления",
    //         "Обувь",
    //         "Обувь на меху",
    //         "Оксфорды",
    //         "Осенняя",
    //         "Пляжная обувь",
    //         "Пляжные",
    //         "Полуботинки",
    //         "Полусапоги",
    //         "Последний размер",
    //         "С открытым носом",
    //         "Сабо",
    //         "Сандалии",
    //         "Сандалии кожаные",
    //         "Сапоги",
    //         "Сапоги и ботинки",
    //         "Сапоги, Полусапожки",
    //         "Сланцы",
    //         "Слипоны",
    //         "Слипоны без каблука",
    //         "Слипоны в стиле casual",
    //         "Сникеры",
    //         "Спортивные",
    //         "Спортивные ботинки",
    //         "Средства для обуви",
    //         "Тапочки",
    //         "Топсайдеры",
    //         "Туфли",
    //         "Туфли без каблука",
    //         "Туфли на каблуке",
    //         "Угги",
    //         "Угги и унты",
    //         "Хайтопы",
    //         "Челси",
    //         "Шлепанцы",
    //         "Шлепанцы кожаные",
    //         "Эспадрильи"
    //       ],
    //       "accessories": [
    //         "Аксессуары для волос",
    //         "Аксессуары для обуви и сумок",
    //         "Ароматы",
    //         "Банданы",
    //         "Береты",
    //         "Бижутерия",
    //         "Браслеты",
    //         "Брелоки",
    //         "Броши",
    //         "Вечерние сумки",
    //         "Воротники",
    //         "Воротники и манжеты",
    //         "Галстуки",
    //         "Головные уборы",
    //         "Гольфы",
    //         "Декор",
    //         "Для волос",
    //         "Дорожные сумки",
    //         "Запонки",
    //         "Защитные маски",
    //         "Из экокожи",
    //         "Кепки",
    //         "Классические носки",
    //         "Клатчи",
    //         "Клатчи и вечерние сумки",
    //         "Кожаные сумки",
    //         "Козырьки",
    //         "Колготки",
    //         "Колье",
    //         "Кольца",
    //         "Кольца и перстни",
    //         "Косметички",
    //         "Кошельки",
    //         "Кошельки кожаные",
    //         "Наручные часы",
    //         "Носки",
    //         "Обложки для документов",
    //         "Обложки и футляры",
    //         "Ободки и заколки",
    //         "Палантины",
    //         "Панамы",
    //         "Парики",
    //         "Перчатки",
    //         "Перчатки демисезонные",
    //         "Перчатки и рукава",
    //         "Платки",
    //         "Повязки",
    //         "Подвески, ожерелья, бусы",
    //         "Подследники",
    //         "Полотенца",
    //         "Постельные принадлежности",
    //         "Пояса",
    //         "Поясные сумки",
    //         "Ремни",
    //         "Ремни и пояса кожаные",
    //         "Ремни и пояса широкие",
    //         "Рюкзаки",
    //         "С рисунками",
    //         "Серьги",
    //         "Снуды",
    //         "Солнцезащитные очки",
    //         "Спортивные сумки",
    //         "Сумки",
    //         "Сумки кожаные",
    //         "Сумки на пояс",
    //         "Сумки через плечо",
    //         "Сумки, Рюкзаки и Кошельки",
    //         "Сумки-планшеты, портфели",
    //         "Сумки-шопперы",
    //         "Украшения на шею",
    //         "Хобо",
    //         "Часы",
    //         "Чехлы",
    //         "Чехлы для наушников",
    //         "Чехлы на гаджеты",
    //         "Шапки",
    //         "Шапки демисезонные",
    //         "Шапки однотонные",
    //         "Шапки, шарфы и перчатки",
    //         "Шарфы",
    //         "Шарфы и платки",
    //         "Шляпы",
    //         "Шопперы"
    //       ]
    //     },
    //     "shops": [
    //       "brandshop",
    //       "brionity",
    //       "lacoste",
    //       "cdek",
    //       "stockmann",
    //       "elyts",
    //       "vipavenue"
    //     ]
    //   }))

    if (data.brands.includes('Все')) data.brands.splice(data.brands.indexOf('Все'), 1)
    if (data.sizes.includes('Все')) data.sizes.splice(data.sizes.indexOf('Все'), 1)

    const gender = { '-men': 'Мужской', '-women': 'Женский', '-unisex': 'unisex', '-child': 'Детский' }
    const category = { clothes: 'Одежда', '2-shoes': 'Обувь', accessories: 'Аксессуары'  }
    const subCategory = { 't-shirts': 'Футболки', 'polo-shirts': 'Футболки Поло', hoodies: 'Толстовки', 'dresses-and-skirts': 'Платья и юбки', sweaters: 'Свитеры', sshirts: 'Рубашки', 'underwear-and-shorts': 'Нижнее белье и шорты', 'new-clothes': 'Новинки', 'blouses-and-shirts': 'Блузы и рубашки', 'gym-shoes': 'Кеды', 'sneakers': 'Кроссовки', 'new-shoes': 'Новые поступления', boots: 'Ботинки', 'bags-backpacks-purses': 'Сумки, Рюкзаки и Кошельки', belts: 'Ремни', perfumery: 'Парфюмерия', caps: 'Кепки', casual: 'Casual', 'a-silhouette': 'А-силуэт', anoraks: 'Анораки', blouses: 'Блузки', blous: 'Блузы', 'blouses-with-print': 'Блузы с принтом', body: 'Боди', 'boyfriends': 'Бойфренды', bombers: 'Бомберы', trousers: 'Брюки', 'narrowed-trousers': 'Брюки зауженные', 'trousers-and-shorts': 'Брюки и шорты', 'cargo-pants': 'Брюки карго', 'classic-trousers': 'Брюки классические', 'leather-trousers': 'Брюки кожаные', 'casual-Trousers': 'Брюки повседневные', 'straight-Trousers': 'Брюки прямые', 'high-rise-trousers': 'Брюки с высокой посадкой', 'loose-fitting-trousers': 'Брюки свободный крой', 'slacks-trousers': 'Брюки слаксы', 'trousers-with-a-standard-fit': 'Брюки со стандартной посадкой', 'sports-trousers': 'Брюки спортивные', 'cropped-trousers': 'Брюки укороченные', 'insulated-trousers': 'Брюки утепленные', 'cotton-Trousers': 'Брюки хлопковые', 'chinos-trousers': 'Брюки чиносы', 'wide-trousers': 'Брюки широкие', 'cargo-Trousers': 'Брюки-карго', bras: 'Бюстгальтеры', 'into-the-cage': 'В клетку', striped: 'В полоску', outerwear: 'Верхняя одежда', windbreakers: 'Ветровки', turtlenecks: 'Водолазки', 'long-Turtlenecks': 'Водолазки длинные', 'plain-Turtlenecks': 'Водолазки однотонные', 'knitted': 'Вязаные', 'ties-and-bow-ties': 'Галстуки и бабочки', 'jeggings': 'Джеггинсы', 'jumpers': 'Джемперы', 'jeans': 'Джинсы', 'boyfriend-jeans': 'Джинсы бойфренды', 'jeans-high-rise': 'Джинсы высокая посадка', 'zayjenny-jeans': 'Джинсы зауженные', 'zipper-jeans': 'Джинсы на молнии', 'straight-Jeans': 'Джинсы прямые', 'skinny-jeans': 'Джинсы скинни', 'cropped-Jeans': 'Джинсы укороченные', 'wide-Jeans': 'Джинсы широкие', 'mom-Jeans': 'Джинсы-момы', 'joggers': 'Джоггеры', 'for-girls': 'Для девочек', 'for-boys': 'Для мальчиков', 'raincoats': 'Дождевики', 'home-Trousers': 'Домашние брюки', 'home-Shorts': 'Домашние шорты', 'home-clothes': 'Домашняя одежда', 'jackets': 'Жакеты', 'jackets and jackets': 'Жакеты и пиджаки', 'Vests': 'Жилеты', 'Denim-Vests': 'Жилеты джинсовые', 'Classic-Vests': 'Жилеты классические', 'Fur-Vests': 'Жилеты меховые', 'quilted-Vests': 'Жилеты стеганые', 'quilteed-Vests': 'Жилеты стёганые', 'Knitted-Vests': 'Жилеты трикотажные', 'Elongated-Vests': 'Жилеты удлиненные', 'Insulated-Vests': 'Жилеты утепленные', 'Narrowed': 'Зауженные', 'Cardigans': 'Кардиганы', 'Long-Cardigan': 'Кардиганы длинные', 'Zip-up-Cardigans': 'Кардиганы на молнии', 'Button-down-Cardigans': 'Кардиганы на пуговицах', 'Oversize-Cardigans': 'Кардиганы оверсайз', 'Caps': 'Кепки', 'Classic': 'Классические', 'Flared': 'Клеш', 'Flareed': 'Клёш', 'Leather': 'Кожаные', 'Overalls': 'Комбинезоны', 'Demi-season-overalls': 'Комбинезоны демисезонные', 'Denim-overalls': 'Комбинезоны джинсовые', 'Overalls-with-trousers': 'Комбинезоны с брюками', 'Overalls-with-shorts': 'Комбинезоны с шортами', 'Suits': 'Костюмы', 'Suits-and-jackets': 'Костюмы и жакеты', 'Classic-suits': 'Костюмы классические', 'Suits-with-trousers': 'Костюмы с брюками', 'Suits-with-skirt': 'Костюмы с юбкой', 'Sports-suits': 'Костюмы спортивные', 'Swimwear': 'Купальники', 'kurtki': 'Куртки', 'Demi-season-jackets': 'Куртки демисезонные', 'Denim-jackets': 'Куртки джинсовые', 'Winter-jackets': 'Куртки зимние', 'Leather-jackets': 'Куртки кожаные', 'Fur-jackets': 'Куртки меховые', 'Oversize-jackets': 'Куртки оверсайз', 'Hooded-jackets': 'Куртки с капюшоном', 'Cropped-Jackets': 'Куртки укороченные', 'Culottes': 'Кюлоты', 'Leggings': 'Леггинсы', 'Sports-Leggings': 'Леггинсы спортивные', 'Legings': 'Легинсы', 'Insulated-Leggings': 'Легинсы утепленные', 'Longsleeves': 'Лонгсливы', 'Sports-leggings': 'Лосины спортивные', 'mayki': 'Майки', 'Maxi': 'Макси', 'Midi': 'Миди', 'Mini': 'Мини', 'Soft': 'Мягкие', 'Capes': 'Накидки', 'Underwear-and-shorts': 'Нижнее белье и шорты', 'New-items': 'Новинки', 'Socks': 'Носки', 'Socks-tights-knee-socks': 'Носки, колготки, гольфы', 'Nightgowns': 'Ночные сорочки', 'Clothes-for-skiing': 'Одежда для горнолыжного спорта', 'Clothes-for-home-and-sleep': 'Одежда для дома и сна', 'Clothes-for-sports': 'Одежда для спорта', 'Olympic': 'Олимпийки', 'Autumn': 'Осенняя', 'Coat': 'Пальто', 'Casual-style-coat': 'Пальто в стиле casual', 'Drape-coats': 'Пальто драповые', 'Plain-coats': 'Пальто однотонные', 'Panama-hats': 'Панамы', 'Pareos': 'Парео', 'Parkas': 'Парки', 'Hooded-parks': 'Парки с капюшоном', 'Elongated-parks': 'Парки удлиненные', 'Pencil cases': 'Пеналы', 'Negligees': 'Пеньюары', 'Jackets': 'Пиджаки', 'Button-down-jackets': 'Пиджаки на пуговицах', 'Jackets-for-jeans': 'Пиджаки под джинсы', 'Pajamas': 'Пижамы', 'Pajamas-and-shirts': 'Пижамы и сорочки', 'Dresses': 'Платья', 'Sleeveless-dresses': 'Платья без рукавов', 'Evening-dresses': 'Платья вечерние', 'Denim-dresses': 'Платья джинсовые', 'Dresses-and-sundresses': 'Платья и сарафаны', 'Dresses-and-skirts': 'Платья и юбки', 'Cocktail-dresses': 'Платья коктейльные', 'Summer-dresses': 'Платья летние', 'Office-dresses': 'Платья офисные', 'Beach-dresses': 'Платья пляжные', 'Dresses-casual': 'Платья повседневные', 'Dresses-with-long-sleeves': 'Платья с длинным рукавом', 'Dresses-with-short-sleeves': 'Платья с коротким рукавом', 'Dresses-with-open-shoulders': 'Платья с открытыми плечами', 'Shirt-dresses': 'Платья-рубашки', 'Raincoats': 'Плащи', 'Demi-season-raincoats': 'Плащи демисезонные', 'Raincoats-and-trench-coats': 'Плащи и тренчи', 'Beach-dresses-and-tunics': 'Пляжные платья и туники', 'Polo': 'Поло', 'Polo-long': 'Поло длинные', 'Plain-Polo': 'Поло однотонные', 'Long-Sleeve-Polo': 'Поло с длинным рукавом', 'Short-sleeve-Polo': 'Поло с коротким рукавом', 'Polo-with-print': 'Поло с принтом', 'Poncho': 'Пончо', 'Poncho-and-capes': 'Пончо и накидки', 'Last-size': 'Последний размер', 'Fitted': 'Приталенные', 'Pullovers': 'Пуловеры', 'Zip-Pullovers': 'Пуловеры на молнии', 'With-V-neck-Pullovers': 'Пуловеры с v-образным вырезом', 'Hooded-Pullovers': 'Пуловеры с капюшоном', 'Round-neck-Pullovers': 'Пуловеры с круглым вырезом', 'Down-jackets': 'Пуховики', 'Demi-season-down-jackets': 'Пуховики демисезонные', 'Oversize-down-jackets': 'Пуховики оверсайз', 'Elongated-down-jackets': 'Пуховики удлиненные', 'Fluffy': 'Пышные', 'Multicolored': 'Разноцветные', 'Shirts': 'Рубашки', 'Denim-shirts': 'Рубашки джинсовые', 'Shirts-and-shirts': 'Рубашки и сорочки', 'Classic-shirts': 'Рубашки классические', 'Oversize-shirts': 'Рубашки оверсайз', 'Fitted-shirts': 'Рубашки приталенные', 'Long-Sleeve-shirts': 'Рубашки с длинным рукавом', 'Short-sleeve-shirts': 'Рубашки с коротким рукавом', 'Elongated-shirts': 'Рубашки удлиненные', 'Polo-shirts': 'Рубашки-поло', 'High-waisted': 'С высокой талией', 'Pinched': 'С защипами', 'Low-rise': 'С низкой посадкой', 'Sundresses': 'Сарафаны', 'Sweaters': 'Свитеры', 'Long-sleeve Sweaters': 'Свитеры с длинным рукавом', 'Sweatshirts': 'Свитшоты', 'Oversize-Sweatshirts': 'Свитшоты оверсайз', 'Printed-Sweatshirts': 'Свитшоты с принтом', 'Sweatshirts-elongated': 'Свитшоты удлиненные', 'Skinny': 'Скинни', 'Tuxedos': 'Смокинги', 'Shirts-and-shirts-long': 'Сорочки и рубашки длинные', 'Shirts-and-shirts-oversize': 'Сорочки и рубашки оверсайз', 'Shirts-and-shirts-plain': 'Сорочки и рубашки однотонные', 'Shirts-and-shirts-with-long-sleeves': 'Сорочки и рубашки с длинным рукавом', 'Sportswear': 'Спортивная одежда', 'Sports': 'Спортивные', 'tracksuits': 'Спортивные костюмы', 'Thermal-underwear': 'Термобелье', 'Long-hoodies': 'Толстовки длинные', 'Hooodies-and-sweatshirts': 'Толстовки и свитшоты', 'Oversize-Hoodies': 'Толстовки оверсайз', 'Solid-color-Hoodies': 'Толстовки однотонные', 'Hooded-Hoodies': 'Толстовки с капюшоном', 'Insulated-Hoodies': 'Толстовки утепленные', 'Tops': 'Топы', 'T-shirts-and-Tops': 'Топы и майки', 'Sports-Tops': 'Топы спортивные', 'Trapezoids': 'Трапеции', 'Raincoats and Trench coats': 'Тренчи и плащи', 'Knitwear': 'Трикотаж', 'Knitted': 'Трикотажные', 'Underpants': 'Трусы', 'Tunics': 'Туники', 'Casual style tunics': 'Туники в стиле casual', 'Button-down tunics': 'Туники на пуговицах', 'Shirt Tunics': 'Туники-рубашки', 'Insulated vests': 'Утепленные жилеты', 'T-shirts': 'Футболки', 'Casual-style-T-shirts': 'Футболки в стиле casual', 'Long-T-shirts': 'Футболки длинные', 'T-shirts-and-T-shirts': 'Футболки и майки', 'Oversize-T-shirts': 'Футболки оверсайз', 'Plain-T-shirts': 'Футболки однотонные', 'Short-Sleeve-T-shirts': 'Футболки с коротким рукавом', 'Printed-T-shirts': 'Футболки с принтом', 'Sports-T-shirts': 'Футболки спортивные', 'Narrow-T-shirts': 'Футболки узкие', 'Khakis': 'Хаки', 'Robes': 'Халаты', 'Hoooodies': 'Худи', 'Long-Hoodies': 'Худи длинные', 'Oversize-Hodies': 'Худи оверсайз', 'Plain-Hoodies': 'Худи однотонные', 'Insulated-Hodies': 'Худи утепленные', 'Chinos': 'Чиносы', 'Stockings-socks-tights': 'Чулки, носки, колготки', 'Hats': 'Шапки', 'School': 'Школа', 'Shorts': 'Шорты', 'Denim-shorts': 'Шорты джинсовые', 'Casual-shorts': 'Шорты повседневные', 'Sports-shorts': 'Шорты спортивные', 'Pants-and-trousers': 'Штаны и брюки', 'Fur-coats-and-sheepskin-coats': 'Шубы и дубленки', 'Skirts': 'Юбки', 'Skirts-without-a-pattern': 'Юбки без рисунка', 'Gode-skirts': 'Юбки годе', 'Denim-skirts': 'Юбки джинсовые', 'Leather-skirts': 'Юбки кожаные', 'Maxi-skirts': 'Юбки макси', 'Midi-Skirts': 'Юбки миди', 'Mini-Skirts': 'Юбки мини', 'Pleated-Skirts': 'Юбки плиссированные', 'Straight-skirts': 'Юбки прямые', 'Narrow-skirts': 'Юбки узкие', 'Wide-skirts': 'Юбки широкие', 'Pencil-skirts': 'Юбки-карандаш', 'Ballet-flats': 'Балетки', 'Leather-ballet-flats': 'Балетки кожаные', 'Without-laces': 'Без шнурков', 'Sandals': 'Босоножки', 'Sandals-with-heels': 'Босоножки на каблуке', 'Wedge-sandals': 'Босоножки на танкетке', 'Sandals-with-straps': 'Босоножки с ремешками', 'Ankle-boots': 'Ботильоны', 'Shoes-without-heels': 'Ботинки без каблука', 'Leather-shoes': 'Ботинки кожаные', 'Casual-shoes': 'Ботинки повседневные', 'Bootijss': 'Ботфорты', 'Brogues': 'Броги', 'Urban': 'Городские', 'Deserts': 'Дезерты', 'Demi-season': 'Демисезонная', 'Derby': 'Дерби', 'Home-shoes': 'Домашняя обувь', 'Dutiki': 'Дутики', 'Womens-shoes': 'Женская обувь', 'Casual-style-Sneakers': 'Кеды в стиле casual', 'Light-sneakers': 'Кеды легкие', 'Sneakers-with-laces': 'Кеды на шнурках', 'Classic-shoes': 'Классические', 'Sneakers': 'Кроссовки', 'Casual-sneakers': 'Кроссовки в стиле casual', 'Suede-sneakers': 'Кроссовки замшевые', 'Summer': 'Летние', 'Loafers': 'Лоферы', 'Moonwalkers': 'Луноходы', 'Mokasini': 'Мокасины', 'Monki': 'Монки', 'Mens-shoes': 'Мужская обувь', 'Mules': 'Мюли', 'High-heels': 'На высоком каблуке', 'Heels': 'На каблуке', 'Platform': 'На платформе', 'Stiletto': 'На шпильке', 'Fur-shoes': 'Обувь на меху', 'Oxfords': 'Оксфорды', 'Autumn-shoes': 'Осенняя', 'Beach-shoes': 'Пляжная обувь', 'Beachs-shoes': 'Пляжные', 'Half-Bootvs': 'Полуботинки', 'Half-Boots': 'Полусапоги', 'Last-size-shoes': 'Последний размер', 'Open-nose': 'С открытым носом', 'Clogs': 'Сабо', 'Sandalses': 'Сандалии', 'Leather-Sandals': 'Сандалии кожаные', 'Boots': 'Сапоги', 'Boots-Half Boots': 'Сапоги, Полусапожки', 'Slates': 'Сланцы', 'Slip-ons': 'Слипоны', 'Slip-ons-without-heels': 'Слипоны без каблука', 'Slip-ons-in-casual-style': 'Слипоны в стиле casual', 'Sneakerss': 'Сникеры', 'Sportes': 'Спортивные', 'Sports-shoes': 'Спортивные ботинки', 'Shoe-products': 'Средства для обуви', 'Slippers': 'Тапочки', 'Topsiders': 'Топсайдеры', 'Shoes': 'Туфли', 'Shoess-without-heels': 'Туфли без каблука', 'Shoes-with-heels': 'Туфли на каблуке', 'Ugg-boots': 'Угги', 'Ugg-boots-and-unts': 'Угги и унты', 'Hightops': 'Хайтопы', 'Chelsea': 'Челси', 'Flip-flops': 'Шлепанцы', 'Leather-Flip-flops': 'Шлепанцы кожаные', 'Espadrilles': 'Эспадрильи', 'Hair-accessories': 'Аксессуары для волос', 'Accessories-for-shoes-and-bags': 'Аксессуары для обуви и сумок', 'Fragrances': 'Ароматы', 'Bandanas': 'Банданы', 'Berets': 'Береты', 'Costume-jewelry': 'Бижутерия', 'Bracelets': 'Браслеты', 'Key-rings': 'Брелоки', 'Brooches': 'Броши', 'Evening-bags': 'Вечерние сумки', 'Collars': 'Воротники', 'Collars-and-Cuffs': 'Воротники и манжеты', 'Ties': 'Галстуки', 'Hateiss': 'Головные уборы', 'Knee-socks': 'Гольфы', 'Hair': 'Для волос', 'Travel-bags': 'Дорожные сумки', 'Cufflinks': 'Запонки', 'Protective-masks': 'Защитные маски', 'From-eco-leather': 'Из экокожи', 'Capess': 'Кепки', 'Classic-socks': 'Классические носки', 'Clutches': 'Клатчи', 'Clutches-and-evening-bags': 'Клатчи и вечерние сумки', 'leather-bags': 'Кожаные сумки', 'Tights': 'Колготки', 'Necklaces': 'Колье', 'Rings': 'Кольца', 'Rings-and-rings': 'Кольца и перстни', 'Cosmetic-bags': 'Косметички', 'Wallets': 'Кошельки', 'Leather-wallets': 'Кошельки кожаные', 'Zippered-wallets': 'Кошельки на молнии', 'Wristwatches': 'Наручные часы', 'Sockess': 'Носки', 'Shortened-socks': 'Носки укороченные', 'Document-covers': 'Обложки для документов', 'Covers-and-cases': 'Обложки и футляры', 'Headbands-and-hairpins': 'Ободки и заколки', 'Stoles': 'Палантины', 'panama-hats': 'Панамы', 'Wigs': 'Парики', 'Gloves-and-Sleeves': 'Перчатки и рукава', 'Leather-gloves': 'Перчатки кожаные', 'Scarves': 'Платки', 'Headbands': 'Повязки', 'Pendant-necklace-beads': 'Подвески, ожерелья, бусы', 'Underclothes': 'Подследники', 'Towels': 'Полотенца', 'Purses': 'Портмоне', 'Bedding': 'Постельные принадлежности', 'Beltess': 'Пояса', 'Waist-bags': 'Поясные сумки', 'Belts': 'Ремни', 'Belts-and-belts': 'Ремни и пояса', 'Leather-belts-and-belts': 'Ремни и пояса кожаные', 'Backpacks': 'Рюкзаки', 'With-zipper': 'С молнией', 'With-drawings': 'С рисунками', 'Earrings': 'Серьги', 'Snoods': 'Снуды', 'Sunglasses': 'Солнцезащитные очки', 'Sports-bags': 'Спортивные сумки', 'Bags': 'Сумки', 'Leather-bags': 'Сумки кожаные', 'Belt-bags': 'Сумки на пояс', 'Shoulder-bags': 'Сумки через плечо', 'Bags-Backpacks-and-Purses': 'Сумки, Рюкзаки и Кошельки', 'Tablet-bags-briefcases': 'Сумки-планшеты, портфели', 'Shoppin-bags-Skateboar': 'Сумки-шопперы', 'products-for-skateboarding': 'Товары для cкейтборда', 'Neck-jewelry': 'Украшения на шею', 'Credit-card-cases': 'Футляры для кредитных карт', 'Hobo': 'Хобо', 'Watch': 'Часы', 'Covers': 'Чехлы', 'Stockings-and-gaiters': 'Чулки и гетры', 'Hateess': 'Шапки', 'Demi-season-hats': 'Шапки демисезонные', 'Plain-hats': 'Шапки однотонные', 'Hats-scarves-and-loves': 'Шапки, шарфы и перчатки', 'Scarvess': 'Шарфы', 'Scarves-and-scarves': 'Шарфы и платки', 'Hatiss': 'Шляпы', }
    const sale = { '-sale-80': 80, '-sale-60': 60, '-sale-50': 50, '-sale-30': 30 }
    const price = { '0-3000': [...Array.from(Array(3000).keys(),x=>x+1)], '3000-5000': [...Array.from(Array(2000).keys(),x=>x+3000)], '5000-7000': [...Array.from(Array(2000).keys(),x=>x+5000)], '7000-10000': [...Array.from(Array(3000).keys(),x=>x+7000)], '10000-9999999': [...Array.from(Array(999999).keys(),x=>x+10000)] }
    const brands = data.brands.reduce((ttlObj, brand) => {
        brand && brand.includes(' ')
          ? ttlObj[`-${brand.replaceAll(' ', '--')}`.toLowerCase()] = brand
          : ttlObj[`-${brand}`.toLowerCase()] = brand
      return ttlObj
      }, {})
    const sizes = data.sizes.reduce((ttlObj, size) => {
      size.includes(' ')
        ? ttlObj[`-${size.replaceAll(' ', '-')}-`.toLowerCase()] = size
        : ttlObj[`-${size}-`.toLowerCase()] = size
      return ttlObj
    }, {})
    const color = { '-black': 'Чёрный', '-white': 'Белый', '-red': 'Красный', '-orange': 'Оранжевый', '-yellow': 'Желтый', '-pink': 'Розовый', '-purple': 'Фиолетовый', '-blue': 'Синий', '-green': 'Зелёный', '-brown': 'Коричневый' }


    const params = paramsArrKeys.reduce((ttlObj,keyParam) => {

      if (keyParam.includes('1-')) Object.keys(gender).forEach(keyGender => {
        if (keyGender === '-child' && keyParam.includes(keyGender)) ttlObj['params.age'] = gender[keyGender]
        else if (keyParam.includes(keyGender)) ttlObj['params.gender'] = gender[keyGender]
      })

      if (keyParam.includes('2-')) {
        Object.keys(category).forEach(keyCategory => {
          if (keyParam.includes(keyCategory)) ttlObj.category = category[keyCategory]
        })
        const subcatArr = keyParam.replace('2-', '').split('--')
        let subcatArr2word,
          subcatArr1word
        subcatArr2word = Object.keys(subCategory)
          .filter(subCategoryName => (subCategoryName.match(/-/g) || []).length > 1)
          .reduce((ttlArr, keySubCat) => {
            if (keyParam.includes(keySubCat)) {
              ttlArr.push(subCategory[keySubCat])
              keyParam = keyParam.replace(keySubCat, '')
            }
            return ttlArr
          }, [])
        subcatArr1word = Object.keys(subCategory)
          .filter(subCategoryName => (subCategoryName.match(/-/g) || []).length <= 1)
          .reduce((ttlArr, keySubCat) => {
            if (keyParam.includes(keySubCat)) {
              ttlArr.push(subCategory[keySubCat])
              keyParam = keyParam.replace(keySubCat, '')
            }
            return ttlArr
          }, [])
        subcatArr2word.push(...subcatArr1word)
        if (subcatArr2word.length !== 0) ttlObj.categoryId = {$in: subcatArr2word}
      }

      if (keyParam.includes('3-')) Object.keys(sale).forEach(keySale => {
        if (keyParam.includes(keySale)) ttlObj.sale = { $gt: sale[keySale] - 1 }
      })

      if (keyParam.includes('4-')) Object.keys(price).forEach(keyPrice => {
        if (keyParam.includes(keyPrice)) ttlObj.price = { $in: price[keyPrice] }
      })

      if (keyParam.includes('5-')) if (keyParam.includes('-instalments-yes')) ttlObj.instalments = true

      if (keyParam.includes('6-')) {
        let brandsArr2word = Object.keys(brands)
          .filter(brandName => brandName.includes('--'))
          .reduce((ttlArr, keyBrand) => {

            if (keyParam.includes(keyBrand)) {
              ttlArr.push(brands[keyBrand])
              keyParam = keyParam.replace(keyBrand, '')
            }

            return ttlArr
          }, [])
        const brandsArr1word = Object.keys(brands)
          .filter(brandName => !brandName.includes('--'))
          .reduce((ttlArr, keyBrand) => {

            if (keyParam.includes(keyBrand)) {
              ttlArr.push(brands[keyBrand])
              keyParam = keyParam.replace(keyBrand, '')
            }

            return ttlArr
          }, [])
        brandsArr2word.push(...brandsArr1word)
        if (brandsArr2word.length !== 0) ttlObj.brand = {$in: brandsArr2word}
      }

      if (keyParam.includes('7-')) {
        const sizesArr = Object.keys(sizes).reduce((ttlArr, keySize) => {
          if (keyParam.includes(keySize)) ttlArr.push(sizes[keySize])
          return ttlArr
        }, [])
        if (sizesArr.length !== 0) ttlObj['params.size'] = {$in: sizesArr}
      }

      if (keyParam.includes('8-')) !keyParam.includes('-delivery-rus') ? ttlObj.delivery = { $in: [ 'Зарубеж', 'Россия' ] } : ttlObj.delivery = 'Россия'

      if (keyParam.includes('91-')) Object.keys(color).forEach(keyColor => {
        if (keyParam.includes(keyColor)) ttlObj['params.color'] = color[keyColor]
      })

      // СЕЛЕКТ "ОТКУДА"
      // if (keyParam.includes('-from-russia')) ttlObj.delivery = 'Россия'
      // if (keyParam.includes('-from-no-russia')) ttlObj.delivery = 'Зарубеж'


      return ttlObj
    }, {})


    const sort = paramsArrKeys.reduce((ttlObj,sortParam) => {

      if (sortParam.includes('expensive')) ttlObj = { price: -1 }
      if (sortParam.includes('cheaper')) ttlObj = { price: 1 }
      if (sortParam.includes('sort-sale')) ttlObj = { sale: -1 }
      if (sortParam.includes('-free-delivery')) ttlObj = { deliveryPrice: 1 }

      return ttlObj
    }, { 'params.rating': -1 })


    // CONNECT DATABASE
    await client.connect()
    const db = await client.db('ss')
    const collection = await db.collection('all')
    products = Object.keys(paramsObj).length === Object.keys({}).length
      ? await collection.find({}).sort({ "params.rating": -1 }).toArray()
      : await collection.find(params).sort(sort).toArray()
    const quantity = products.length


    // PAGINATION LOGIC
    const pageParams = paramsArrKeys.reduce((pageParamsObj, param) => {
      if (param.includes('page')) {
        const pageArr = param.split('-')
        pageParamsObj.page = pageArr[1]
      }
      if (param.includes('show')) {
        const showArr = param.split('-')
        pageParamsObj.show = showArr[1]
      }
      return pageParamsObj
    }, {})
    const count = +pageParams.show || 60
    for (let s = 0, e = count; s < products.length; s += count, e += count)
      result.push(products.slice(s, +e))

    return {
      products: result[pageParams.page - 1 || 0],
      quantity
    }
  } catch (e) {
    console.log(e);
  }
}
